### ISSUE TITLE
Reinstall COE Cluster

### ISSUE THREAD

**Issue by rbo** [stormshift/support#122]
Because of IP overlapping & SSD Disk Upgrade of master nodes we have to reinstall COE Cluster

### ToDo's - before Shutting down the cluster:
- [x] Move NetApp Trident configuration into git / gitops
- [x] right before shutdown: must-gather configuration
- [x] Backup RDP vm
- [x] Get RDP vm running at inf49 for example or my laptop ;-) 

### ToDo, 2023-02-15
- [x] Remove rj49 wire from inf49
- [x] Shutdown master nodes and replace Disks with SSD's - start with one and test ;-)

### Prepare Env.
- [x] Rollout air-gapped VLan ad the switches (VLAN ID 69, coe-air-gapped)
- [x] Define Network and [Document](https://docs.google.com/spreadsheets/d/1iwXilV1V84IQN7mKOIHq28-9P5bWabN019TJPaJ_3Es/edit#gid=1735312685)  - 192.168.69.0/24
- [x] Prepare Bastion Host (RHEL9  + VLAN + COE)
- [x] Add NetApp Info Air-gapped network
- [x] Define DNS Name structure
  - [x] Mirror registry 
- [x] Request certificates mirror regiistry
#### Prepare Bastion Host
- [x] DNS
- [ ] Proxy
   - [ ] Block All
   - [ ] Allow Red Hat SSO
   - [ ] GitHub 
- [x] Load Balancer
- [x] DHCPD
- [x] Mirror Registry

### After shutdown
- [x] Replace Disk with SSD's at Controle-plane nodes
- [ ] ...
- [ ] Inform @astolzen to clean PV/PVC at the external CEPTH

### Configure new Cluster
- [ ] Second interface without an IP Address at COE NEtwork
- [ ] Add disco logo ;-)

**Comment by rbo** [comment]
#### Configure vlan
```
arista-rj45(config)#vlan 69
arista-rj45(config-vlan-69)#name coe-air-gapped
arista-rj45(config-vlan-69)#end
arista-rj45#write memory
Copy completed successfully.
arista-rj45#copy running-config startup-config 
Copy completed successfully.
arista-rj45#

arista-sfp>enable 
arista-sfp#configure 
arista-sfp(config)#vlan 69
arista-sfp(config-vlan-69)#name coe-air-gapped
arista-sfp(config-vlan-69)#end
arista-sfp#write memory 
Copy completed successfully.
arista-sfp#copy running-config startup-config 
Copy completed successfully.
arista-sfp#
```

**Comment by rbo** [comment]
### Inf49 configured with two wires, primary standard network secondary air-gapped:
```
arista-sfp(config-if-Et28/4)#switchport access vlan 69
arista-sfp(config-if-Et28/4)#show running-config interfaces Ethernet 28/4
interface Ethernet28/4
   description inf49 secondary ens2f1
   switchport access vlan 69
   switchport trunk native vlan 32
   switchport trunk allowed vlan 9,32
   switchport
arista-sfp(config-if-Et28/4)#no switchport trunk native vlan 32
arista-sfp(config-if-Et28/4)#no switchport trunk allowed vlan 9,32
arista-sfp(config-if-Et28/4)#show running-config interfaces Ethernet 28/4
interface Ethernet28/4
   description inf49 secondary ens2f1
   switchport access vlan 69
   switchport
arista-sfp(config-if-Et28/4)#

arista-sfp(config-if-Et28/4)#show running-config interfaces Ethernet 28/1-4
interface Ethernet28/1
   switchport trunk native vlan 32
   switchport trunk allowed vlan 9,32
   switchport mode trunk
   switchport
interface Ethernet28/2
   description inf49 primary ens2f0
   switchport trunk native vlan 32
   switchport trunk allowed vlan 9,32
   switchport mode trunk
   switchport
interface Ethernet28/3
   switchport trunk native vlan 32
   switchport trunk allowed vlan 9,32
   switchport mode trunk
   switchport
interface Ethernet28/4
   description inf49 secondary ens2f1
   switchport access vlan 69
   switchport
arista-sfp(config-if-Et28/4)#show interfaces Ethernet 28/1-4 status 
Port       Name                   Status       Vlan     Duplex Speed  Type         Flags Encapsulation
Et28/1                            notconnect   trunk    full   10G    40GBASE-CR4                    
Et28/2     inf49 primary ens2f0   connected    trunk    full   10G    40GBASE-CR4                    
Et28/3                            connected    trunk    full   10G    40GBASE-CR4                    
Et28/4     inf49 secondary ens2f1 connected    69       full   10G    40GBASE-CR4                    

arista-sfp(config-if-Et28/4)#

```

**Comment by rbo** [comment]
### Inf4,Inf5,Inf6 ins VLAN 69 gehangen.
```
arista-sfp(config-if-Et8/2)#show running-config interface Ethernet 8/1-4
interface Ethernet8/1
   description inf6
   switchport access vlan 69
   switchport
interface Ethernet8/2
   switchport trunk native vlan 32
   switchport trunk allowed vlan 9,32
   switchport mode trunk
   switchport
interface Ethernet8/3
   description inf5
   switchport access vlan 69
   switchport
interface Ethernet8/4
   description inf4
   switchport access vlan 69
   switchport
arista-sfp(config-if-Et8/2)#
```

**Comment by rbo** [comment]
### Added NetApp into vlan 69 
and created a disco storage VM in vlan 69

Switch arista-rj45 & arista-sfp configured to access vlan 69 ad port channel 10 and netapp ports.

**Comment by rbo** [comment]
### Added inf7/8 into disco vlan

<details>
  <summary>Details</summary>
 
```
arista-rj45#show running-config interfaces Ethernet 9-10
interface Ethernet9
   description inf8-primary
   switchport trunk native vlan 32
   switchport trunk allowed vlan 9,32
   switchport mode trunk
interface Ethernet10
   description inf7-primary
   switchport trunk native vlan 32
   switchport trunk allowed vlan 9,32
   switchport mode trunk
arista-rj45#configure interfaces Ethernet 9-10
% Invalid input
arista-rj45#configure 
arista-rj45(config)#interface  Ethernet 9-10
arista-rj45(config-if-Et9-10)#switchport access vlan 69
arista-rj45(config-if-Et9-10)#no switchport mode trunk
arista-rj45(config-if-Et9-10)#no switchport trunk allowed vlan 9,32
arista-rj45(config-if-Et9-10)#no switchport trunk native vlan 32
arista-rj45(config-if-Et9-10)#show running-config interfaces Ethernet 9-10
interface Ethernet9
   description inf8-primary
   switchport access vlan 69
interface Ethernet10
   description inf7-primary
   switchport access vlan 69
arista-rj45(config-if-Et9-10)#write memory 
Copy completed successfully.
arista-rj45(config-if-Et9-10)#copy running-config startup-config 
Copy completed successfully.
arista-rj45(config-if-Et9-10)#
arista-rj45(config-if-Et7-8)#show interfaces  Ethernet 7-10 status
Port       Name              Status       Vlan        Duplex  Speed Type        
Et7        inf8-secondary    disabled     trunk         auto   auto 10GBASE-T   
Et8        inf7-secondary    disabled     trunk         auto   auto 10GBASE-T   
Et9        inf8-primary      connected    69          a-full  a-10G 10GBASE-T   
Et10       inf7-primary      connected    69          a-full  a-10G 10GBASE-T   

```

</details>
